export enum Technology {
  JAVASCRIPT = 'JavaScript',
  REACTJS = 'ReactJS',
  NEXTJS = 'NextJs',
  ANGULARJS = 'AngularJS',
  ANGULAR = 'Angular',
  HTML = 'HTML',
  CSS = 'CSS',
  SCSS = 'SCSS',
  JAVA = 'Java',
  BOOTSTRAP = 'Bootstrap',
  REACTBOOTSTRAP = 'R-Bootstrap',
  VITE = 'Vite',
  TILEWIND = 'TileWind',
  FIGMA = 'Figma',
  MATERIALUI = 'MaterialUI',
  WORDPRESS = 'Wordpress',
  ELEMENTOR = 'Elementor',
  DATABASES = 'Databases',
  C = 'C#',
  MONGODB = 'MongoDB',
  NODEJS = 'NodeJS',
  EXPRESSJS = 'ExpressJs',
  MERN = 'MERN',
  GIT = 'GIT',
}

export enum BaseButtonText {
  CONTACTME = 'CONTACT ME',
  VIEWPROJECT = 'VIEW PROJECT',
  VIEWCODE = 'VIEW CODE',
  SENDMESSAGE = 'SEND MESSAGE',
}
