export enum Technology {
  JAVASCRIPT = 'JavaScript',
  TYPESCRIPT = 'TypeScript',
  REACTJS = 'React',
  NEXTJS = 'Next.js',
  SUPABASE = 'Supabase',
  VERCEL = 'Vercel',
  ANGULARJS = 'AngularJS',
  ANGULAR = 'Angular',
  HTML = 'HTML',
  CSS = 'CSS',
  SCSS = 'SCSS',
  JAVA = 'Java',
  BOOTSTRAP = 'Bootstrap',
  REACTBOOTSTRAP = 'R-Bootstrap',
  VITE = 'Vite',
  TAILWIND = 'Tailwind CSS',
  FIGMA = 'Figma',
  MATERIALUI = 'Material UI',
  WORDPRESS = 'WordPress',
  ELEMENTOR = 'Elementor',
  C = 'C#',
  MONGODB = 'MongoDB',
  NODEJS = 'Node.js',
  EXPRESSJS = 'Express',
  MERN = 'MERN',
  GIT = 'Git',
}

export enum BaseButtonText {
  CONTACTME = 'CONTACT ME',
  VIEWPROJECT = 'VIEW PROJECT',
  VIEWCODE = 'VIEW CODE',
  SENDMESSAGE = 'SEND MESSAGE',
}
